openapi: 3.0.0
info:
  title: Watned-pre-onboarding
  description: 원티드 프리 온보딩 백엔드 인턴쉽을 위한 api 명세서
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /users/register:
    post:
      summary: 회원가입
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
      responses:
        "201":
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  userId:
                    type: integer
                    example: 1
        "400":
          description: 요청 형식이 잘못되었습니다.
        "500":
          description: 서버 오류
  /users/login:
    post:
      summary: 로그인
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  token:
                    type: string
                    example: "your-jwt-token-string"
        "400":
          description: 요청 형식이 잘못되었습니다.
        "401":
          description: 유효하지 않은 이메일 또는 비밀번호입니다.
        "500":
          description: 서버 오류
  /users/logout:
    post:
      summary: 로그아웃
      tags:
        - Users
      responses:
        "200":
          description: 로그아웃 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: "로그아웃 되었습니다."
        "500":
          description: 서버 오류
  /posts:
    post:
      summary: 게시물 생성
      tags:
        - Posts
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              example:
                title: 새로운 게시물
                content: 게시물 내용입니다.
      responses:
        "201":
          description: 게시물이 등록되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: "게시물이 등록되었습니다."
                  postId:
                    type: integer
                    example: 1
        "400":
          description: 제목과 내용은 필수 입력 항목입니다.
        "401":
          description: 인증되지 않은 사용자입니다.
        "500":
          description: 서버 오류
  paths:
  /posts/all:
    get:
      summary: 전체 게시물 조회 (페이징 가능)
      tags:
        - Posts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: 페이지 번호 (기본값: 1)
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
          description: 한 페이지에 표시할 게시물 수 (기본값: 10)
      responses:
        '200':
          description: 게시물 조회에 성공했습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalPosts:
                    type: integer
                  currentPage:
                    type: integer
                  pageSize:
                    type: integer
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
        '500':
          description: 서버 오류
  /posts/{postId}:
    get:
      summary: 게시물 조회
      tags:
        - Posts
      parameters:
        - in: path
          name: postId
          schema:
            type: integer
          required: true
          description: 게시물 ID
      responses:
        "200":
          description: 게시물 조회에 성공했습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: "게시물 조회에 성공했습니다."
                  post:
                    type: object
                    properties:
                      id:
                        type: integer
                      title:
                        type: string
                      content:
                        type: string
                    example:
                      id: 1
                      title: 게시물 제목
                      content: 게시물 내용입니다.
        "404":
          description: 게시물을 찾을 수 없습니다.
        "500":
          description: 서버 오류
  /posts/{postId}/update:
    patch:
      summary: 게시물 수정
      tags:
        - Posts
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: postId
          schema:
            type: integer
          required: true
          description: 게시물 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              example:
                title: 수정된 게시물
                content: 수정된 게시물 내용입니다.
      responses:
        "201":
          description: 게시물 수정이 완료되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: "게시물 수정이 완료되었습니다."
                  result:
                    type: object
                    properties:
                      title:
                        type: string
                      content:
                        type: string
                    example:
                      title: 수정된 게시물
                      content: 수정된 게시물 내용입니다.
        "401":
          description: 인증되지 않은 사용자입니다.
        "403":
          description: 수정 권한이 없습니다.
        "404":
          description: 게시물을 찾을 수 없습니다.
        "500":
          description: 서버 오류
  /posts/{postId}/delete:
    delete:
      summary: 게시물 삭제
      tags:
        - Posts
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: postId
          schema:
            type: integer
          required: true
          description: 게시물 ID
      responses:
        "200":
          description: 게시물 삭제가 완료되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: "게시물 삭제가 완료되었습니다."
        "401":
          description: 인증되지 않은 사용자입니다.
        "403":
          description: 삭제 권한이 없습니다.
        "404":
          description: 게시물을 찾을 수 없습니다.
        "500":
          description: 서버 오류
